version: 2
jobs:
  py-dna-test:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: run-python-tests
          command: cd py-dna && python3 -m unittest discover
  scala-dna-test:
    docker:
      - image: hseeberger/scala-sbt:8u141-jdk_2.12.3_0.13.16
    steps:
      - checkout
      - restore_cache:
          keys:
            - proj-{{ checksum "scala-dna/build.sbt" }}
            - proj-
      - run:
          name: run-scala-tests
          command: |
            cd scala-dna
            sbt compile
            sbt test
      - save_cache:
          key: proj-{{ checksum "scala-dna/build.sbt" }}
          paths:
            - scala-dna/target
            - scala-dna/project/target
workflows:
  version: 2
  test_all:
    jobs:
      - py-dna-test
      - scala-dna-test
