version: 2
jobs:
  py-dna-test:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: run-python-tests
          command: cd py-dna && python3 -m unittest discover
  scala-dna-test:
    docker:
      - image: hseeberger/scala-sbt:8u141-jdk_2.12.3_0.13.16
    steps:
      - checkout
      - restore_cache:
          keys:
            - proj2-{{ checksum "scala-dna/build.sbt" }}
            - proj2-
      - run:
          name: run-scala-tests
          command: |
            cd scala-dna
            # sbt compile
            # sbt test
      - save_cache:
          key: proj2-{{ checksum "scala-dna/build.sbt" }}
          paths:
            - "scala-dna/target"
            - "scala-dna/project/target"
            - "scala-dna/.ivy2/cache"
            - "scala-dna/.sbt"
            - "scala-dna/.m2"
workflows:
  version: 2
  test_all:
    jobs:
      - py-dna-test
      - scala-dna-test
